Add new datetime shortcut, update timezone info
TeskaLabs/splang-docs pull request #18
Opened 2024-05-02 12:38 UTC by bochkver

2024-05-03 06:48 UTC, mejroslav requested changes

2024-05-03 06:48 UTC, mejroslav commented on docs/expressions/parsec/parser.md
> +
Consider different section ordering:

1. ISO 8601 - "datetime standard"
2. RFC 3339
3. RFC 3164

2024-05-03 06:48 UTC, mejroslav commented on docs/expressions/parsec/parser.md
> +Timezone can be parsed from the input string or set up in the lmio-parsec configuration.
Timezone can be parsed from the input string, or, if not present, it can be set in LogMan.io Parsec configuration.

2024-05-03 06:48 UTC, mejroslav commented on docs/expressions/parsec/parser.md
> +Year is provided by the _smart year_ function. Timezone can be set up in the lmio-parsec configuration.
I would like to describe somewhere what is _smart year_ and include a link here.

2024-05-03 06:48 UTC, mejroslav commented on docs/expressions/parsec/parser.md
> +Year is provided by the _smart year_ function. Timezone can be set up in the lmio-parsec configuration.
Timezone must be set up in LogMan.io Parsec configuration, otherwise considered as UTC.

2024-05-09 10:16 UTC, ateska submitted a review, later dismissed
I agree with the ordering based on the "preferred" formats.
Otherwise mergeable.

2024-05-10 12:49 UTC, mejroslav approved these changes

2024-05-10 12:51 UTC, merged